### ISSUE TITLE
HTTPs problem

### ISSUE THREAD

**Issue by NickS55** [gevhaz/hugo-theme-notrack#2] opened 2021-06-06 15:44 UTC
I really liked the design of this page and wanted to use it with github pages. It looks like when I try to use Https there is an error with how files are called in index.html. I believe this is because stylesheets, imgs, etc... are called using the form `<link rel="stylesheet" type="text/css" href="http://USERNAME.github.io/css/fonts.css">`. Instead of having https it uses http this causes browsers to block CSS and other files.

**Comment by Najrim** [comment] 2021-06-07 10:41
Glad you like it :)

What does it look like when you try to use it? Is it just that the fonts don't load? I'll see if I can reproduce.

Did you set `baseURL` in your config file to use https? If the problem is what you are suggesting, [this](https://github.com/gevhaz/hugo-theme-notrack/blob/80916c2ddf43d98c7df2299ae8d6cbd2d488306b/layouts/partials/head.html#L4) would be the offending line in the theme. It uses `absURL` to create the link, which in turn uses your `baseURL` from the config. In your case, I think it should be:

`config.yaml`:

`baseURL = "https://NickS55.github.io/"`

**Comment by gevhaz** [comment] 2021-06-07 10:43
Glad you like it :)

What does it look like when you try to use it? Is it just that the fonts don't load? I'll see if I can reproduce.

Did you set `baseURL` in your config file to use https? If the problem is what you are suggesting, [this](https://github.com/gevhaz/hugo-theme-notrack/blob/80916c2ddf43d98c7df2299ae8d6cbd2d488306b/layouts/partials/head.html#L4) would be the offending line in the theme. It uses `absURL` to create the link, which in turn uses your `baseURL` from the config. In your case, I think it should be:

`config.yaml`:

`baseURL = "https://NickS55.github.io/"`

**Comment by NickS55** [comment] 2021-06-10 04:12
Hey Gevhaz, thanks for the response. I ended up using a different theme. However, When I made my baseURL I made sure it was https://..., but for some reason the resulting html used http:// which seemed to cause problems.

**Comment by gevhaz** [comment] 2021-06-10 10:59
Okay, that's good to know. I'll see what I can find.

**Comment by gevhaz** [comment] 2022-05-01 21:01
Closing due to not being able to reproduce.

**Closed by gevhaz** 2022-05-01 21:01 UTC
