### ISSUE TITLE
It ignores the footer template

### ISSUE THREAD

**Issue by repvlsion** [gevhaz/hugo-theme-notrack#8] opened 2022-07-12 15:45 UTC
I've tried to add a footer by modifying `themes/notrack/layouts/partials/footer.html` but it ignores the changes. Quite weird since changing `themes/notrack/layouts/partials/header.html` works.

I've tried with a clean site using your exampleSite but same issue. What I've tried is to add a <p> tag with a copyright notice, but no luck. I've also tried adding other tags but none of them work.

**Comment by gevhaz** [comment] 2022-07-15 22:44
Hi, thanks for the support :) 

The problem is that I didn't actually use the footer partial in `layout/_default/baseof.html` (unlike the header). I added a pull request for fixing it #9. Do you mind checking it out and see if it's what your looking for (and whether you can see any unexpected behavior)?

Just clone the repo, check out the `add-footer` branch and add something to the new `footer` parameter in the config for your site.

**Comment by gevhaz** [comment] 2022-07-15 22:45
In what way is the rss "social" not working?

**Comment by gevhaz** [comment] 2022-07-18 21:20
> And after adding the rss parameter it doesn't appear in when using the shortcodes, while other social links works fine. Not a big issue tbh.

Oh, ok that's a problem. I'll open another ticket for that and close this with the footer fix. RSS goes with the philosophy of the theme so that should absolutely be fixed.

**Closed** 2022-07-18 21:20 UTC

**Comment by gevhaz** [comment] 2022-07-27 20:21
@repvlsion, the RSS issue should be fixed now if you use the latest master branch :)
